### ISSUE TITLE
ffmpeg repository error on provisioning

### ISSUE THREAD

**Issue by hnarayanan** [jcalazan/ansible-django-stack#25]
I ran into the following when I attempted to use this playbook. The repository pointed to doesn't exist and I am not able to find a suitable replacement.

```
TASK: [web | Add a custom repository for ffmpeg] ****************************** 
failed: [default] => {"failed": true, "parsed": false}
BECOME-SUCCESS-kipofcbjoqsbuaicrsiwoqujiigbueas
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1434537365.12-129649650050245/apt_repository", line 2524, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1434537365.12-129649650050245/apt_repository", line 436, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/deprecation.py", line 98, in deprecated_function
    return func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 418, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch http://ppa.launchpad.net/jon-severinsson/ffmpeg/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found
, W:Failed to fetch http://ppa.launchpad.net/jon-severinsson/ffmpeg/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found
, E:Some index files failed to download. They have been ignored, or old ones used instead.

```

**Comment by jcalazan** [comment]
@hnarayanan Are you using Ubuntu 12.04 x64?

**Comment by hnarayanan** [comment]
Yes, but not by conscious choice. I simply downloaded the repo and did a `vagrant up` which seems to use `precise64.box`.

```
repo='deb http://ppa.launchpad.net/kirillshkrogalev/ffmpeg-next/ubuntu {{ ansible_distribution_release }} main'
```

(I haven't checked it yet because I'm currently being thwarted at a subsequent step because https://www.rabbitmq.com/ is down.)

**Comment by hnarayanan** [comment]
I'm somewhat confused.

I re-cloned this repository and `vagrant up` worked beautifully out of the box. Furthermore, I see no reference to this `ppa.launchpad.net/jon-severinsson/ffmpeg...` URL in the code (which I could swear I did before). So I close this issue and apologise for the noise.

**Comment by jcalazan** [comment]
No problem @hnarayanan, maybe it was an issue with the apt server.
